[package]
name = "docker-fdb"
version = "0.1.0"
edition = "2021"

[dependencies]
foundationdb = { version = "0.9.0", features = ["embedded-fdb-include", "fdb-7_3"] }
tokio = { version = "1.37.0", features = ["rt-multi-thread", "macros"] }
eyre = "0.6.12"
