services:
  foundationdb:
    environment:
      FDB_NETWORKING_MODE: container
    image: foundationdb/foundationdb:7.3.27
    hostname: "foundationdb"
    ports:
      - "4500:4500"
  cli:
    build:
      dockerfile: cli.dockerfile
    stdin_open: true
    tty: true
  lab:
    build:
      dockerfile: app.dockerfile
    stdin_open: true
    tty: true